### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by timoxley** [hughsk/npm-metadata-raw#1]
Just FYI. Understand this is old, perhaps should deprecate.

Slightly adapted code from readme:

``` js
var db = require('level')(__dirname + '/npm-meta')
var metadata = require('npm-metadata-raw')
var sublevel = require('level-sublevel')

var metadb = metadata(sublevel(db))

function inspect(item) { // for debugging
  console.log(require('util').inspect(item, {colors: true, depth: 30}))
}


metadb.sync(err => {
  if (err) throw err
  console.log('synced')
  metadb.get('disc', function(err, meta) {
    if (err) throw err
    inspect(JSON.parse(meta))
  })
})
.on('found', name => {
  console.info('found', name)
})
.on('data', (json, name, date) => {
  console.info('data', name, date)
})

```

Expected some 'data' or 'found' output, but only got 'synced' after about 30s, and apparently no results:

```
> time node index.js
synced
/Users/timoxley/Projects/nodesource/webinar/universal-javascript/index.js:15
    if (err) throw err
             ^
NotFoundError: Key not found in database
    at /Users/timoxley/Projects/nodesource/webinar/universal-javascript/node_modules/level-sublevel/shell.js:101:18
    at /Users/timoxley/Projects/nodesource/webinar/universal-javascript/node_modules/level-sublevel/nut.js:120:19
node index.js  0.27s user 0.04s system 0% cpu 1:15.94 total
```

Looks like nothing made it into the db:

```
> du -h npm-meta/*
  0B    npm-meta/000011.log
4.0K    npm-meta/CURRENT
  0B    npm-meta/LOCK
4.0K    npm-meta/LOG
4.0K    npm-meta/LOG.old
4.0K    npm-meta/MANIFEST-000010
```

**Comment by hughsk** [comment]
Damn, that's a bummer — deprecating seems like the way to go for now at least. Have included a link in the message to https://skimdb.npmjs.com/registry/_design/scratch/_view/byField which is a much speedier option either way :)

**Comment by ainthek** [comment]
does the link: https://skimdb.npmjs.com/registry/_design/scratch/_view/byField works ?
< HTTP/2 404
< date: Wed, 23 Oct 2019 10:29:05 GMT
< npm-notice: this endpoint is deprecated
< server: haproxy
